### ISSUE TITLE
fdg_img depends on an old version of fdg-sim

### ISSUE THREAD

**Issue by Bjohnson131** [grantshandy/fdg#14]
Hello, it seems fdg_img depends on 0.8.0 of fdg_sim, but the most recent is 0.9.1. Could this be upgraded please? :)

**Comment by grantshandy** [comment]
@Bjohnson131 [got it !](https://crates.io/crates/fdg-img/0.4.2/dependencies)

Sorry, this project is in a bit of disrepair. I'm going to re-work it for a 1.0 👍🏽.

**Comment by Bjohnson131** [comment]
@grantshandy Thank you! I'm working on a rust integration with obsidian (http://obsidian.md), and this is a core functionality. The  Effort is highly appreciated!
