### ISSUE TITLE
Add node to names to .svg images

### ISSUE THREAD

**Issue by wainwrightmark** [grantshandy/fdg#3]
Hi. I've been playing around with this package - finding it very useful.  

I needed to display the node names so I hacked it in myself.
```rust
//around line 167 of gen_image/lib.rs
let text_style = TextStyle::from(("sans-serif", 20).into_font());
let coord = (node.location.x as i32, node.location.y as i32);
backend.draw_text(node.name.as_str(), &text_style, (coord.0 + 10, coord.1 - 10))?;
```

I think it might be a useful feature to add. Obviously with settings to control the style etc. Let me know if you agree and you'd like me to do a PR?

**Comment by grantshandy** [comment]
Sure this sounds like a great idea. I'd love for you to create a PR.

**Comment by grantshandy** [comment]
I rewrote a lot of `fdg-img`'s coordinate-translating/finding in 1363189ffc3a9a9df7c842e3eb1cc27c5d72fc3a so it will never cut off the node text now (it did quite often before, especially when using different forces). I hope you find that useful.

Thanks for your contribution!
