### ISSUE TITLE
Allow for adding custom forces

### ISSUE THREAD

**Issue by djahandarie** [grantshandy/fdg#6]
Right now it's hard to define a new `Force` outside of the crate due to the fields of `Force` being private. Could they be made public?

**Comment by grantshandy** [comment]
Sorry for not getting around to this sooner. Sure, I'll make those fields public and push a new minor release to fdg-sim tonight.

**Comment by grantshandy** [comment]
@djahandarie I've just published a new version 0.9.1 with public fields on `Force`. 👍🏽
